# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a086263ae5fa34b494acc822898c5e5523c3d6b785f9002f3a7edafa79cdc0167638aac5e769552cb4d160855020c641d14d9bb237d1b95e013e99db9127ba0

test:
  secret_key_base: 20596c7a0b3facaf80af03195bf09525f229da3ac5c4e035ccaa2c06e8aa4d5787b7ad2c02fa4c400de2c032dbbdf98d199a02622b661e615a8a822aabfb790e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
